add isort to the lint API.

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -56,11 +56,22 @@ jobs:
           git config --local user.name "GitHub Action"
           git add .
           
-          CHANGED_FILES=$(git diff --name-only | wc -l)
-          # avoid "nothing to commit" error.
-          echo "Prepare to commit $CHANGED_FILES"
-          if [ "$CHANGED_FILES" -gt "0" ]; then
-              echo "Commiting $CHANGED_FILES"
-              git commit -m "[CI-Lint] Fix code style issues with black" -a
-              git push  
+          git diff --exit-code --quiet
+          CHANGES=$?
+
+          # If there are changes (exit code is not 0), commit and push
+          if [ $CHANGES -ne 0 ]; then
+              git add .
+              git commit -m "Commit message for the changes"
+              git push origin main
+          else
+              echo "No changes to commit."
           fi
+          # CHANGED_FILES=$(git diff --name-only | wc -l)
+          # # avoid "nothing to commit" error.
+          # echo "Prepare to commit $CHANGED_FILES"
+          # if [ "$CHANGED_FILES" -gt "0" ]; then
+          #     echo "Commiting $CHANGED_FILES"
+          #     git commit -m "[CI-Lint] Fix code style issues with black" -a
+          #     git push  
+          # fi
